// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db_message.proto

#ifndef PROTOBUF_db_5fmessage_2eproto__INCLUDED
#define PROTOBUF_db_5fmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_db_5fmessage_2eproto();
void protobuf_AssignDesc_db_5fmessage_2eproto();
void protobuf_ShutdownFile_db_5fmessage_2eproto();


enum DB_MESSAGE_DEFINE {
  DB_MSG_GET_USER_INFO = 0,
  DB_MSG_UPDATE_USER_INFO = 1
};
bool DB_MESSAGE_DEFINE_IsValid(int value);
const DB_MESSAGE_DEFINE DB_MESSAGE_DEFINE_MIN = DB_MSG_GET_USER_INFO;
const DB_MESSAGE_DEFINE DB_MESSAGE_DEFINE_MAX = DB_MSG_UPDATE_USER_INFO;
const int DB_MESSAGE_DEFINE_ARRAYSIZE = DB_MESSAGE_DEFINE_MAX + 1;

const ::google::protobuf::EnumDescriptor* DB_MESSAGE_DEFINE_descriptor();
inline const ::std::string& DB_MESSAGE_DEFINE_Name(DB_MESSAGE_DEFINE value) {
  return ::google::protobuf::internal::NameOfEnum(
    DB_MESSAGE_DEFINE_descriptor(), value);
}
inline bool DB_MESSAGE_DEFINE_Parse(
    const ::std::string& name, DB_MESSAGE_DEFINE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DB_MESSAGE_DEFINE>(
    DB_MESSAGE_DEFINE_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DB_MESSAGE_DEFINE>() {
  return ::DB_MESSAGE_DEFINE_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_db_5fmessage_2eproto__INCLUDED
