// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "db_message.pb.h"
#include "tb_user.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_message_2eproto();
void protobuf_AssignDesc_message_2eproto();
void protobuf_ShutdownFile_message_2eproto();

class PosInfo;
class PlayerInfo;
class NpcInfo;
class ClientHeartBeatRequest;
class ClientHeartBeatResponse;
class ClientLoginRequest;
class ClientLoginResponse;
class ClientInitNotf;
class ClientMoveRequest;
class ClientMoveResponse;
class PlayerLeaveViewNotf;
class LeavePlayersViewNotf;
class PlayerEnterViewNotf;
class EnterPlayersViewNotf;

enum MSG_ACTION_TYPE {
  MSG_REQUEST = 0,
  MSG_RESPONSE = 1,
  MSG_NOTIFY = 2
};
bool MSG_ACTION_TYPE_IsValid(int value);
const MSG_ACTION_TYPE MSG_ACTION_TYPE_MIN = MSG_REQUEST;
const MSG_ACTION_TYPE MSG_ACTION_TYPE_MAX = MSG_NOTIFY;
const int MSG_ACTION_TYPE_ARRAYSIZE = MSG_ACTION_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* MSG_ACTION_TYPE_descriptor();
inline const ::std::string& MSG_ACTION_TYPE_Name(MSG_ACTION_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    MSG_ACTION_TYPE_descriptor(), value);
}
inline bool MSG_ACTION_TYPE_Parse(
    const ::std::string& name, MSG_ACTION_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MSG_ACTION_TYPE>(
    MSG_ACTION_TYPE_descriptor(), name, value);
}
enum MessageType {
  MSG_SOCCER_PLAYER_INFO = 1,
  MSG_HEART_BEAT = 2,
  MSG_CLIENT_LOGIN = 3,
  MSG_GATE_SERVER_REGISTER = 4,
  MSG_INIT_CLIENT = 5,
  MSG_CLIENT_MOVE = 6,
  MSG_PLAYER_LEAVE_VIEW_NOTF = 7,
  MSG_LEAVE_PLAYERS_VIEW_NOTF = 8,
  MSG_PLAYER_ENTER_VIEW_NOTF = 9,
  MSG_ENTER_PLAYERS_VIEW_NOTF = 10
};
bool MessageType_IsValid(int value);
const MessageType MessageType_MIN = MSG_SOCCER_PLAYER_INFO;
const MessageType MessageType_MAX = MSG_ENTER_PLAYERS_VIEW_NOTF;
const int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageType_descriptor();
inline const ::std::string& MessageType_Name(MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageType_descriptor(), value);
}
inline bool MessageType_Parse(
    const ::std::string& name, MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
enum DbMessageType {
  MSG_DB_COMMON = 10000
};
bool DbMessageType_IsValid(int value);
const DbMessageType DbMessageType_MIN = MSG_DB_COMMON;
const DbMessageType DbMessageType_MAX = MSG_DB_COMMON;
const int DbMessageType_ARRAYSIZE = DbMessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* DbMessageType_descriptor();
inline const ::std::string& DbMessageType_Name(DbMessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    DbMessageType_descriptor(), value);
}
inline bool DbMessageType_Parse(
    const ::std::string& name, DbMessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DbMessageType>(
    DbMessageType_descriptor(), name, value);
}
// ===================================================================

class PosInfo : public ::google::protobuf::Message {
 public:
  PosInfo();
  virtual ~PosInfo();

  PosInfo(const PosInfo& from);

  inline PosInfo& operator=(const PosInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PosInfo& default_instance();

  void Swap(PosInfo* other);

  // implements Message ----------------------------------------------

  PosInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PosInfo& from);
  void MergeFrom(const PosInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // required int32 y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PosInfo)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static PosInfo* default_instance_;
};
// -------------------------------------------------------------------

class PlayerInfo : public ::google::protobuf::Message {
 public:
  PlayerInfo();
  virtual ~PlayerInfo();

  PlayerInfo(const PlayerInfo& from);

  inline PlayerInfo& operator=(const PlayerInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerInfo& default_instance();

  void Swap(PlayerInfo* other);

  // implements Message ----------------------------------------------

  PlayerInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayerInfo& from);
  void MergeFrom(const PlayerInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 player_id = 1;
  inline bool has_player_id() const;
  inline void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  inline ::google::protobuf::int32 player_id() const;
  inline void set_player_id(::google::protobuf::int32 value);

  // required string player_nickname = 2;
  inline bool has_player_nickname() const;
  inline void clear_player_nickname();
  static const int kPlayerNicknameFieldNumber = 2;
  inline const ::std::string& player_nickname() const;
  inline void set_player_nickname(const ::std::string& value);
  inline void set_player_nickname(const char* value);
  inline void set_player_nickname(const char* value, size_t size);
  inline ::std::string* mutable_player_nickname();
  inline ::std::string* release_player_nickname();
  inline void set_allocated_player_nickname(::std::string* player_nickname);

  // required int32 player_level = 3;
  inline bool has_player_level() const;
  inline void clear_player_level();
  static const int kPlayerLevelFieldNumber = 3;
  inline ::google::protobuf::int32 player_level() const;
  inline void set_player_level(::google::protobuf::int32 value);

  // required int32 career_id = 4;
  inline bool has_career_id() const;
  inline void clear_career_id();
  static const int kCareerIdFieldNumber = 4;
  inline ::google::protobuf::int32 career_id() const;
  inline void set_career_id(::google::protobuf::int32 value);

  // required int32 player_status = 5;
  inline bool has_player_status() const;
  inline void clear_player_status();
  static const int kPlayerStatusFieldNumber = 5;
  inline ::google::protobuf::int32 player_status() const;
  inline void set_player_status(::google::protobuf::int32 value);

  // required .PosInfo pos = 6;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 6;
  inline const ::PosInfo& pos() const;
  inline ::PosInfo* mutable_pos();
  inline ::PosInfo* release_pos();
  inline void set_allocated_pos(::PosInfo* pos);

  // @@protoc_insertion_point(class_scope:PlayerInfo)
 private:
  inline void set_has_player_id();
  inline void clear_has_player_id();
  inline void set_has_player_nickname();
  inline void clear_has_player_nickname();
  inline void set_has_player_level();
  inline void clear_has_player_level();
  inline void set_has_career_id();
  inline void clear_has_career_id();
  inline void set_has_player_status();
  inline void clear_has_player_status();
  inline void set_has_pos();
  inline void clear_has_pos();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* player_nickname_;
  ::google::protobuf::int32 player_id_;
  ::google::protobuf::int32 player_level_;
  ::google::protobuf::int32 career_id_;
  ::google::protobuf::int32 player_status_;
  ::PosInfo* pos_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static PlayerInfo* default_instance_;
};
// -------------------------------------------------------------------

class NpcInfo : public ::google::protobuf::Message {
 public:
  NpcInfo();
  virtual ~NpcInfo();

  NpcInfo(const NpcInfo& from);

  inline NpcInfo& operator=(const NpcInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NpcInfo& default_instance();

  void Swap(NpcInfo* other);

  // implements Message ----------------------------------------------

  NpcInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NpcInfo& from);
  void MergeFrom(const NpcInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 npc_id = 1;
  inline bool has_npc_id() const;
  inline void clear_npc_id();
  static const int kNpcIdFieldNumber = 1;
  inline ::google::protobuf::int32 npc_id() const;
  inline void set_npc_id(::google::protobuf::int32 value);

  // required string npc_nickname = 2;
  inline bool has_npc_nickname() const;
  inline void clear_npc_nickname();
  static const int kNpcNicknameFieldNumber = 2;
  inline const ::std::string& npc_nickname() const;
  inline void set_npc_nickname(const ::std::string& value);
  inline void set_npc_nickname(const char* value);
  inline void set_npc_nickname(const char* value, size_t size);
  inline ::std::string* mutable_npc_nickname();
  inline ::std::string* release_npc_nickname();
  inline void set_allocated_npc_nickname(::std::string* npc_nickname);

  // required int32 npc_level = 3;
  inline bool has_npc_level() const;
  inline void clear_npc_level();
  static const int kNpcLevelFieldNumber = 3;
  inline ::google::protobuf::int32 npc_level() const;
  inline void set_npc_level(::google::protobuf::int32 value);

  // required int32 totoal_hp = 4;
  inline bool has_totoal_hp() const;
  inline void clear_totoal_hp();
  static const int kTotoalHpFieldNumber = 4;
  inline ::google::protobuf::int32 totoal_hp() const;
  inline void set_totoal_hp(::google::protobuf::int32 value);

  // required int32 current_hp = 5;
  inline bool has_current_hp() const;
  inline void clear_current_hp();
  static const int kCurrentHpFieldNumber = 5;
  inline ::google::protobuf::int32 current_hp() const;
  inline void set_current_hp(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NpcInfo)
 private:
  inline void set_has_npc_id();
  inline void clear_has_npc_id();
  inline void set_has_npc_nickname();
  inline void clear_has_npc_nickname();
  inline void set_has_npc_level();
  inline void clear_has_npc_level();
  inline void set_has_totoal_hp();
  inline void clear_has_totoal_hp();
  inline void set_has_current_hp();
  inline void clear_has_current_hp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* npc_nickname_;
  ::google::protobuf::int32 npc_id_;
  ::google::protobuf::int32 npc_level_;
  ::google::protobuf::int32 totoal_hp_;
  ::google::protobuf::int32 current_hp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static NpcInfo* default_instance_;
};
// -------------------------------------------------------------------

class ClientHeartBeatRequest : public ::google::protobuf::Message {
 public:
  ClientHeartBeatRequest();
  virtual ~ClientHeartBeatRequest();

  ClientHeartBeatRequest(const ClientHeartBeatRequest& from);

  inline ClientHeartBeatRequest& operator=(const ClientHeartBeatRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientHeartBeatRequest& default_instance();

  void Swap(ClientHeartBeatRequest* other);

  // implements Message ----------------------------------------------

  ClientHeartBeatRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientHeartBeatRequest& from);
  void MergeFrom(const ClientHeartBeatRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 client_time = 1;
  inline bool has_client_time() const;
  inline void clear_client_time();
  static const int kClientTimeFieldNumber = 1;
  inline ::google::protobuf::int32 client_time() const;
  inline void set_client_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ClientHeartBeatRequest)
 private:
  inline void set_has_client_time();
  inline void clear_has_client_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 client_time_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static ClientHeartBeatRequest* default_instance_;
};
// -------------------------------------------------------------------

class ClientHeartBeatResponse : public ::google::protobuf::Message {
 public:
  ClientHeartBeatResponse();
  virtual ~ClientHeartBeatResponse();

  ClientHeartBeatResponse(const ClientHeartBeatResponse& from);

  inline ClientHeartBeatResponse& operator=(const ClientHeartBeatResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientHeartBeatResponse& default_instance();

  void Swap(ClientHeartBeatResponse* other);

  // implements Message ----------------------------------------------

  ClientHeartBeatResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientHeartBeatResponse& from);
  void MergeFrom(const ClientHeartBeatResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 server_time = 1;
  inline bool has_server_time() const;
  inline void clear_server_time();
  static const int kServerTimeFieldNumber = 1;
  inline ::google::protobuf::int32 server_time() const;
  inline void set_server_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ClientHeartBeatResponse)
 private:
  inline void set_has_server_time();
  inline void clear_has_server_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 server_time_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static ClientHeartBeatResponse* default_instance_;
};
// -------------------------------------------------------------------

class ClientLoginRequest : public ::google::protobuf::Message {
 public:
  ClientLoginRequest();
  virtual ~ClientLoginRequest();

  ClientLoginRequest(const ClientLoginRequest& from);

  inline ClientLoginRequest& operator=(const ClientLoginRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientLoginRequest& default_instance();

  void Swap(ClientLoginRequest* other);

  // implements Message ----------------------------------------------

  ClientLoginRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientLoginRequest& from);
  void MergeFrom(const ClientLoginRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 role_id = 1;
  inline bool has_role_id() const;
  inline void clear_role_id();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::int32 role_id() const;
  inline void set_role_id(::google::protobuf::int32 value);

  // required string token = 2;
  inline bool has_token() const;
  inline void clear_token();
  static const int kTokenFieldNumber = 2;
  inline const ::std::string& token() const;
  inline void set_token(const ::std::string& value);
  inline void set_token(const char* value);
  inline void set_token(const char* value, size_t size);
  inline ::std::string* mutable_token();
  inline ::std::string* release_token();
  inline void set_allocated_token(::std::string* token);

  // @@protoc_insertion_point(class_scope:ClientLoginRequest)
 private:
  inline void set_has_role_id();
  inline void clear_has_role_id();
  inline void set_has_token();
  inline void clear_has_token();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* token_;
  ::google::protobuf::int32 role_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static ClientLoginRequest* default_instance_;
};
// -------------------------------------------------------------------

class ClientLoginResponse : public ::google::protobuf::Message {
 public:
  ClientLoginResponse();
  virtual ~ClientLoginResponse();

  ClientLoginResponse(const ClientLoginResponse& from);

  inline ClientLoginResponse& operator=(const ClientLoginResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientLoginResponse& default_instance();

  void Swap(ClientLoginResponse* other);

  // implements Message ----------------------------------------------

  ClientLoginResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientLoginResponse& from);
  void MergeFrom(const ClientLoginResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ClientLoginResponse)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 ret_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static ClientLoginResponse* default_instance_;
};
// -------------------------------------------------------------------

class ClientInitNotf : public ::google::protobuf::Message {
 public:
  ClientInitNotf();
  virtual ~ClientInitNotf();

  ClientInitNotf(const ClientInitNotf& from);

  inline ClientInitNotf& operator=(const ClientInitNotf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientInitNotf& default_instance();

  void Swap(ClientInitNotf* other);

  // implements Message ----------------------------------------------

  ClientInitNotf* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientInitNotf& from);
  void MergeFrom(const ClientInitNotf& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);

  // required .db_tb_user user_info = 2;
  inline bool has_user_info() const;
  inline void clear_user_info();
  static const int kUserInfoFieldNumber = 2;
  inline const ::db_tb_user& user_info() const;
  inline ::db_tb_user* mutable_user_info();
  inline ::db_tb_user* release_user_info();
  inline void set_allocated_user_info(::db_tb_user* user_info);

  // @@protoc_insertion_point(class_scope:ClientInitNotf)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();
  inline void set_has_user_info();
  inline void clear_has_user_info();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::db_tb_user* user_info_;
  ::google::protobuf::int32 ret_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static ClientInitNotf* default_instance_;
};
// -------------------------------------------------------------------

class ClientMoveRequest : public ::google::protobuf::Message {
 public:
  ClientMoveRequest();
  virtual ~ClientMoveRequest();

  ClientMoveRequest(const ClientMoveRequest& from);

  inline ClientMoveRequest& operator=(const ClientMoveRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientMoveRequest& default_instance();

  void Swap(ClientMoveRequest* other);

  // implements Message ----------------------------------------------

  ClientMoveRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientMoveRequest& from);
  void MergeFrom(const ClientMoveRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 map_id = 1;
  inline bool has_map_id() const;
  inline void clear_map_id();
  static const int kMapIdFieldNumber = 1;
  inline ::google::protobuf::int32 map_id() const;
  inline void set_map_id(::google::protobuf::int32 value);

  // required int32 pos_x = 2;
  inline bool has_pos_x() const;
  inline void clear_pos_x();
  static const int kPosXFieldNumber = 2;
  inline ::google::protobuf::int32 pos_x() const;
  inline void set_pos_x(::google::protobuf::int32 value);

  // required int32 pos_y = 3;
  inline bool has_pos_y() const;
  inline void clear_pos_y();
  static const int kPosYFieldNumber = 3;
  inline ::google::protobuf::int32 pos_y() const;
  inline void set_pos_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ClientMoveRequest)
 private:
  inline void set_has_map_id();
  inline void clear_has_map_id();
  inline void set_has_pos_x();
  inline void clear_has_pos_x();
  inline void set_has_pos_y();
  inline void clear_has_pos_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 map_id_;
  ::google::protobuf::int32 pos_x_;
  ::google::protobuf::int32 pos_y_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static ClientMoveRequest* default_instance_;
};
// -------------------------------------------------------------------

class ClientMoveResponse : public ::google::protobuf::Message {
 public:
  ClientMoveResponse();
  virtual ~ClientMoveResponse();

  ClientMoveResponse(const ClientMoveResponse& from);

  inline ClientMoveResponse& operator=(const ClientMoveResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientMoveResponse& default_instance();

  void Swap(ClientMoveResponse* other);

  // implements Message ----------------------------------------------

  ClientMoveResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientMoveResponse& from);
  void MergeFrom(const ClientMoveResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);

  // required int32 map_id = 2;
  inline bool has_map_id() const;
  inline void clear_map_id();
  static const int kMapIdFieldNumber = 2;
  inline ::google::protobuf::int32 map_id() const;
  inline void set_map_id(::google::protobuf::int32 value);

  // required int32 pos_x = 3;
  inline bool has_pos_x() const;
  inline void clear_pos_x();
  static const int kPosXFieldNumber = 3;
  inline ::google::protobuf::int32 pos_x() const;
  inline void set_pos_x(::google::protobuf::int32 value);

  // required int32 pos_y = 4;
  inline bool has_pos_y() const;
  inline void clear_pos_y();
  static const int kPosYFieldNumber = 4;
  inline ::google::protobuf::int32 pos_y() const;
  inline void set_pos_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ClientMoveResponse)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();
  inline void set_has_map_id();
  inline void clear_has_map_id();
  inline void set_has_pos_x();
  inline void clear_has_pos_x();
  inline void set_has_pos_y();
  inline void clear_has_pos_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 ret_;
  ::google::protobuf::int32 map_id_;
  ::google::protobuf::int32 pos_x_;
  ::google::protobuf::int32 pos_y_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static ClientMoveResponse* default_instance_;
};
// -------------------------------------------------------------------

class PlayerLeaveViewNotf : public ::google::protobuf::Message {
 public:
  PlayerLeaveViewNotf();
  virtual ~PlayerLeaveViewNotf();

  PlayerLeaveViewNotf(const PlayerLeaveViewNotf& from);

  inline PlayerLeaveViewNotf& operator=(const PlayerLeaveViewNotf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerLeaveViewNotf& default_instance();

  void Swap(PlayerLeaveViewNotf* other);

  // implements Message ----------------------------------------------

  PlayerLeaveViewNotf* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayerLeaveViewNotf& from);
  void MergeFrom(const PlayerLeaveViewNotf& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 player_id = 1;
  inline bool has_player_id() const;
  inline void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  inline ::google::protobuf::int32 player_id() const;
  inline void set_player_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PlayerLeaveViewNotf)
 private:
  inline void set_has_player_id();
  inline void clear_has_player_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 player_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static PlayerLeaveViewNotf* default_instance_;
};
// -------------------------------------------------------------------

class LeavePlayersViewNotf : public ::google::protobuf::Message {
 public:
  LeavePlayersViewNotf();
  virtual ~LeavePlayersViewNotf();

  LeavePlayersViewNotf(const LeavePlayersViewNotf& from);

  inline LeavePlayersViewNotf& operator=(const LeavePlayersViewNotf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LeavePlayersViewNotf& default_instance();

  void Swap(LeavePlayersViewNotf* other);

  // implements Message ----------------------------------------------

  LeavePlayersViewNotf* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LeavePlayersViewNotf& from);
  void MergeFrom(const LeavePlayersViewNotf& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 player_id = 1;
  inline int player_id_size() const;
  inline void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  inline ::google::protobuf::int32 player_id(int index) const;
  inline void set_player_id(int index, ::google::protobuf::int32 value);
  inline void add_player_id(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      player_id() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_player_id();

  // @@protoc_insertion_point(class_scope:LeavePlayersViewNotf)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > player_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static LeavePlayersViewNotf* default_instance_;
};
// -------------------------------------------------------------------

class PlayerEnterViewNotf : public ::google::protobuf::Message {
 public:
  PlayerEnterViewNotf();
  virtual ~PlayerEnterViewNotf();

  PlayerEnterViewNotf(const PlayerEnterViewNotf& from);

  inline PlayerEnterViewNotf& operator=(const PlayerEnterViewNotf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerEnterViewNotf& default_instance();

  void Swap(PlayerEnterViewNotf* other);

  // implements Message ----------------------------------------------

  PlayerEnterViewNotf* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayerEnterViewNotf& from);
  void MergeFrom(const PlayerEnterViewNotf& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .PlayerInfo player_info = 1;
  inline bool has_player_info() const;
  inline void clear_player_info();
  static const int kPlayerInfoFieldNumber = 1;
  inline const ::PlayerInfo& player_info() const;
  inline ::PlayerInfo* mutable_player_info();
  inline ::PlayerInfo* release_player_info();
  inline void set_allocated_player_info(::PlayerInfo* player_info);

  // @@protoc_insertion_point(class_scope:PlayerEnterViewNotf)
 private:
  inline void set_has_player_info();
  inline void clear_has_player_info();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::PlayerInfo* player_info_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static PlayerEnterViewNotf* default_instance_;
};
// -------------------------------------------------------------------

class EnterPlayersViewNotf : public ::google::protobuf::Message {
 public:
  EnterPlayersViewNotf();
  virtual ~EnterPlayersViewNotf();

  EnterPlayersViewNotf(const EnterPlayersViewNotf& from);

  inline EnterPlayersViewNotf& operator=(const EnterPlayersViewNotf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const EnterPlayersViewNotf& default_instance();

  void Swap(EnterPlayersViewNotf* other);

  // implements Message ----------------------------------------------

  EnterPlayersViewNotf* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const EnterPlayersViewNotf& from);
  void MergeFrom(const EnterPlayersViewNotf& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .PlayerInfo player_info = 1;
  inline int player_info_size() const;
  inline void clear_player_info();
  static const int kPlayerInfoFieldNumber = 1;
  inline const ::PlayerInfo& player_info(int index) const;
  inline ::PlayerInfo* mutable_player_info(int index);
  inline ::PlayerInfo* add_player_info();
  inline const ::google::protobuf::RepeatedPtrField< ::PlayerInfo >&
      player_info() const;
  inline ::google::protobuf::RepeatedPtrField< ::PlayerInfo >*
      mutable_player_info();

  // @@protoc_insertion_point(class_scope:EnterPlayersViewNotf)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::PlayerInfo > player_info_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static EnterPlayersViewNotf* default_instance_;
};
// ===================================================================


// ===================================================================

// PosInfo

// required int32 x = 1;
inline bool PosInfo::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PosInfo::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PosInfo::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PosInfo::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 PosInfo::x() const {
  return x_;
}
inline void PosInfo::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// required int32 y = 2;
inline bool PosInfo::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PosInfo::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PosInfo::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PosInfo::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 PosInfo::y() const {
  return y_;
}
inline void PosInfo::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// -------------------------------------------------------------------

// PlayerInfo

// required int32 player_id = 1;
inline bool PlayerInfo::has_player_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayerInfo::set_has_player_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayerInfo::clear_has_player_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayerInfo::clear_player_id() {
  player_id_ = 0;
  clear_has_player_id();
}
inline ::google::protobuf::int32 PlayerInfo::player_id() const {
  return player_id_;
}
inline void PlayerInfo::set_player_id(::google::protobuf::int32 value) {
  set_has_player_id();
  player_id_ = value;
}

// required string player_nickname = 2;
inline bool PlayerInfo::has_player_nickname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PlayerInfo::set_has_player_nickname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PlayerInfo::clear_has_player_nickname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PlayerInfo::clear_player_nickname() {
  if (player_nickname_ != &::google::protobuf::internal::kEmptyString) {
    player_nickname_->clear();
  }
  clear_has_player_nickname();
}
inline const ::std::string& PlayerInfo::player_nickname() const {
  return *player_nickname_;
}
inline void PlayerInfo::set_player_nickname(const ::std::string& value) {
  set_has_player_nickname();
  if (player_nickname_ == &::google::protobuf::internal::kEmptyString) {
    player_nickname_ = new ::std::string;
  }
  player_nickname_->assign(value);
}
inline void PlayerInfo::set_player_nickname(const char* value) {
  set_has_player_nickname();
  if (player_nickname_ == &::google::protobuf::internal::kEmptyString) {
    player_nickname_ = new ::std::string;
  }
  player_nickname_->assign(value);
}
inline void PlayerInfo::set_player_nickname(const char* value, size_t size) {
  set_has_player_nickname();
  if (player_nickname_ == &::google::protobuf::internal::kEmptyString) {
    player_nickname_ = new ::std::string;
  }
  player_nickname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PlayerInfo::mutable_player_nickname() {
  set_has_player_nickname();
  if (player_nickname_ == &::google::protobuf::internal::kEmptyString) {
    player_nickname_ = new ::std::string;
  }
  return player_nickname_;
}
inline ::std::string* PlayerInfo::release_player_nickname() {
  clear_has_player_nickname();
  if (player_nickname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = player_nickname_;
    player_nickname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PlayerInfo::set_allocated_player_nickname(::std::string* player_nickname) {
  if (player_nickname_ != &::google::protobuf::internal::kEmptyString) {
    delete player_nickname_;
  }
  if (player_nickname) {
    set_has_player_nickname();
    player_nickname_ = player_nickname;
  } else {
    clear_has_player_nickname();
    player_nickname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 player_level = 3;
inline bool PlayerInfo::has_player_level() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PlayerInfo::set_has_player_level() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PlayerInfo::clear_has_player_level() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PlayerInfo::clear_player_level() {
  player_level_ = 0;
  clear_has_player_level();
}
inline ::google::protobuf::int32 PlayerInfo::player_level() const {
  return player_level_;
}
inline void PlayerInfo::set_player_level(::google::protobuf::int32 value) {
  set_has_player_level();
  player_level_ = value;
}

// required int32 career_id = 4;
inline bool PlayerInfo::has_career_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PlayerInfo::set_has_career_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PlayerInfo::clear_has_career_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PlayerInfo::clear_career_id() {
  career_id_ = 0;
  clear_has_career_id();
}
inline ::google::protobuf::int32 PlayerInfo::career_id() const {
  return career_id_;
}
inline void PlayerInfo::set_career_id(::google::protobuf::int32 value) {
  set_has_career_id();
  career_id_ = value;
}

// required int32 player_status = 5;
inline bool PlayerInfo::has_player_status() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PlayerInfo::set_has_player_status() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PlayerInfo::clear_has_player_status() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PlayerInfo::clear_player_status() {
  player_status_ = 0;
  clear_has_player_status();
}
inline ::google::protobuf::int32 PlayerInfo::player_status() const {
  return player_status_;
}
inline void PlayerInfo::set_player_status(::google::protobuf::int32 value) {
  set_has_player_status();
  player_status_ = value;
}

// required .PosInfo pos = 6;
inline bool PlayerInfo::has_pos() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PlayerInfo::set_has_pos() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PlayerInfo::clear_has_pos() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PlayerInfo::clear_pos() {
  if (pos_ != NULL) pos_->::PosInfo::Clear();
  clear_has_pos();
}
inline const ::PosInfo& PlayerInfo::pos() const {
  return pos_ != NULL ? *pos_ : *default_instance_->pos_;
}
inline ::PosInfo* PlayerInfo::mutable_pos() {
  set_has_pos();
  if (pos_ == NULL) pos_ = new ::PosInfo;
  return pos_;
}
inline ::PosInfo* PlayerInfo::release_pos() {
  clear_has_pos();
  ::PosInfo* temp = pos_;
  pos_ = NULL;
  return temp;
}
inline void PlayerInfo::set_allocated_pos(::PosInfo* pos) {
  delete pos_;
  pos_ = pos;
  if (pos) {
    set_has_pos();
  } else {
    clear_has_pos();
  }
}

// -------------------------------------------------------------------

// NpcInfo

// required int32 npc_id = 1;
inline bool NpcInfo::has_npc_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NpcInfo::set_has_npc_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NpcInfo::clear_has_npc_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NpcInfo::clear_npc_id() {
  npc_id_ = 0;
  clear_has_npc_id();
}
inline ::google::protobuf::int32 NpcInfo::npc_id() const {
  return npc_id_;
}
inline void NpcInfo::set_npc_id(::google::protobuf::int32 value) {
  set_has_npc_id();
  npc_id_ = value;
}

// required string npc_nickname = 2;
inline bool NpcInfo::has_npc_nickname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NpcInfo::set_has_npc_nickname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NpcInfo::clear_has_npc_nickname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NpcInfo::clear_npc_nickname() {
  if (npc_nickname_ != &::google::protobuf::internal::kEmptyString) {
    npc_nickname_->clear();
  }
  clear_has_npc_nickname();
}
inline const ::std::string& NpcInfo::npc_nickname() const {
  return *npc_nickname_;
}
inline void NpcInfo::set_npc_nickname(const ::std::string& value) {
  set_has_npc_nickname();
  if (npc_nickname_ == &::google::protobuf::internal::kEmptyString) {
    npc_nickname_ = new ::std::string;
  }
  npc_nickname_->assign(value);
}
inline void NpcInfo::set_npc_nickname(const char* value) {
  set_has_npc_nickname();
  if (npc_nickname_ == &::google::protobuf::internal::kEmptyString) {
    npc_nickname_ = new ::std::string;
  }
  npc_nickname_->assign(value);
}
inline void NpcInfo::set_npc_nickname(const char* value, size_t size) {
  set_has_npc_nickname();
  if (npc_nickname_ == &::google::protobuf::internal::kEmptyString) {
    npc_nickname_ = new ::std::string;
  }
  npc_nickname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* NpcInfo::mutable_npc_nickname() {
  set_has_npc_nickname();
  if (npc_nickname_ == &::google::protobuf::internal::kEmptyString) {
    npc_nickname_ = new ::std::string;
  }
  return npc_nickname_;
}
inline ::std::string* NpcInfo::release_npc_nickname() {
  clear_has_npc_nickname();
  if (npc_nickname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = npc_nickname_;
    npc_nickname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void NpcInfo::set_allocated_npc_nickname(::std::string* npc_nickname) {
  if (npc_nickname_ != &::google::protobuf::internal::kEmptyString) {
    delete npc_nickname_;
  }
  if (npc_nickname) {
    set_has_npc_nickname();
    npc_nickname_ = npc_nickname;
  } else {
    clear_has_npc_nickname();
    npc_nickname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 npc_level = 3;
inline bool NpcInfo::has_npc_level() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NpcInfo::set_has_npc_level() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NpcInfo::clear_has_npc_level() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NpcInfo::clear_npc_level() {
  npc_level_ = 0;
  clear_has_npc_level();
}
inline ::google::protobuf::int32 NpcInfo::npc_level() const {
  return npc_level_;
}
inline void NpcInfo::set_npc_level(::google::protobuf::int32 value) {
  set_has_npc_level();
  npc_level_ = value;
}

// required int32 totoal_hp = 4;
inline bool NpcInfo::has_totoal_hp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void NpcInfo::set_has_totoal_hp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void NpcInfo::clear_has_totoal_hp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void NpcInfo::clear_totoal_hp() {
  totoal_hp_ = 0;
  clear_has_totoal_hp();
}
inline ::google::protobuf::int32 NpcInfo::totoal_hp() const {
  return totoal_hp_;
}
inline void NpcInfo::set_totoal_hp(::google::protobuf::int32 value) {
  set_has_totoal_hp();
  totoal_hp_ = value;
}

// required int32 current_hp = 5;
inline bool NpcInfo::has_current_hp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void NpcInfo::set_has_current_hp() {
  _has_bits_[0] |= 0x00000010u;
}
inline void NpcInfo::clear_has_current_hp() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void NpcInfo::clear_current_hp() {
  current_hp_ = 0;
  clear_has_current_hp();
}
inline ::google::protobuf::int32 NpcInfo::current_hp() const {
  return current_hp_;
}
inline void NpcInfo::set_current_hp(::google::protobuf::int32 value) {
  set_has_current_hp();
  current_hp_ = value;
}

// -------------------------------------------------------------------

// ClientHeartBeatRequest

// required int32 client_time = 1;
inline bool ClientHeartBeatRequest::has_client_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClientHeartBeatRequest::set_has_client_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClientHeartBeatRequest::clear_has_client_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClientHeartBeatRequest::clear_client_time() {
  client_time_ = 0;
  clear_has_client_time();
}
inline ::google::protobuf::int32 ClientHeartBeatRequest::client_time() const {
  return client_time_;
}
inline void ClientHeartBeatRequest::set_client_time(::google::protobuf::int32 value) {
  set_has_client_time();
  client_time_ = value;
}

// -------------------------------------------------------------------

// ClientHeartBeatResponse

// required int32 server_time = 1;
inline bool ClientHeartBeatResponse::has_server_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClientHeartBeatResponse::set_has_server_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClientHeartBeatResponse::clear_has_server_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClientHeartBeatResponse::clear_server_time() {
  server_time_ = 0;
  clear_has_server_time();
}
inline ::google::protobuf::int32 ClientHeartBeatResponse::server_time() const {
  return server_time_;
}
inline void ClientHeartBeatResponse::set_server_time(::google::protobuf::int32 value) {
  set_has_server_time();
  server_time_ = value;
}

// -------------------------------------------------------------------

// ClientLoginRequest

// required int32 role_id = 1;
inline bool ClientLoginRequest::has_role_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClientLoginRequest::set_has_role_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClientLoginRequest::clear_has_role_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClientLoginRequest::clear_role_id() {
  role_id_ = 0;
  clear_has_role_id();
}
inline ::google::protobuf::int32 ClientLoginRequest::role_id() const {
  return role_id_;
}
inline void ClientLoginRequest::set_role_id(::google::protobuf::int32 value) {
  set_has_role_id();
  role_id_ = value;
}

// required string token = 2;
inline bool ClientLoginRequest::has_token() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ClientLoginRequest::set_has_token() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ClientLoginRequest::clear_has_token() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ClientLoginRequest::clear_token() {
  if (token_ != &::google::protobuf::internal::kEmptyString) {
    token_->clear();
  }
  clear_has_token();
}
inline const ::std::string& ClientLoginRequest::token() const {
  return *token_;
}
inline void ClientLoginRequest::set_token(const ::std::string& value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::kEmptyString) {
    token_ = new ::std::string;
  }
  token_->assign(value);
}
inline void ClientLoginRequest::set_token(const char* value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::kEmptyString) {
    token_ = new ::std::string;
  }
  token_->assign(value);
}
inline void ClientLoginRequest::set_token(const char* value, size_t size) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::kEmptyString) {
    token_ = new ::std::string;
  }
  token_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ClientLoginRequest::mutable_token() {
  set_has_token();
  if (token_ == &::google::protobuf::internal::kEmptyString) {
    token_ = new ::std::string;
  }
  return token_;
}
inline ::std::string* ClientLoginRequest::release_token() {
  clear_has_token();
  if (token_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = token_;
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ClientLoginRequest::set_allocated_token(::std::string* token) {
  if (token_ != &::google::protobuf::internal::kEmptyString) {
    delete token_;
  }
  if (token) {
    set_has_token();
    token_ = token;
  } else {
    clear_has_token();
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// ClientLoginResponse

// required int32 ret = 1;
inline bool ClientLoginResponse::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClientLoginResponse::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClientLoginResponse::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClientLoginResponse::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 ClientLoginResponse::ret() const {
  return ret_;
}
inline void ClientLoginResponse::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
}

// -------------------------------------------------------------------

// ClientInitNotf

// required int32 ret = 1;
inline bool ClientInitNotf::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClientInitNotf::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClientInitNotf::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClientInitNotf::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 ClientInitNotf::ret() const {
  return ret_;
}
inline void ClientInitNotf::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
}

// required .db_tb_user user_info = 2;
inline bool ClientInitNotf::has_user_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ClientInitNotf::set_has_user_info() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ClientInitNotf::clear_has_user_info() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ClientInitNotf::clear_user_info() {
  if (user_info_ != NULL) user_info_->::db_tb_user::Clear();
  clear_has_user_info();
}
inline const ::db_tb_user& ClientInitNotf::user_info() const {
  return user_info_ != NULL ? *user_info_ : *default_instance_->user_info_;
}
inline ::db_tb_user* ClientInitNotf::mutable_user_info() {
  set_has_user_info();
  if (user_info_ == NULL) user_info_ = new ::db_tb_user;
  return user_info_;
}
inline ::db_tb_user* ClientInitNotf::release_user_info() {
  clear_has_user_info();
  ::db_tb_user* temp = user_info_;
  user_info_ = NULL;
  return temp;
}
inline void ClientInitNotf::set_allocated_user_info(::db_tb_user* user_info) {
  delete user_info_;
  user_info_ = user_info;
  if (user_info) {
    set_has_user_info();
  } else {
    clear_has_user_info();
  }
}

// -------------------------------------------------------------------

// ClientMoveRequest

// required int32 map_id = 1;
inline bool ClientMoveRequest::has_map_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClientMoveRequest::set_has_map_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClientMoveRequest::clear_has_map_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClientMoveRequest::clear_map_id() {
  map_id_ = 0;
  clear_has_map_id();
}
inline ::google::protobuf::int32 ClientMoveRequest::map_id() const {
  return map_id_;
}
inline void ClientMoveRequest::set_map_id(::google::protobuf::int32 value) {
  set_has_map_id();
  map_id_ = value;
}

// required int32 pos_x = 2;
inline bool ClientMoveRequest::has_pos_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ClientMoveRequest::set_has_pos_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ClientMoveRequest::clear_has_pos_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ClientMoveRequest::clear_pos_x() {
  pos_x_ = 0;
  clear_has_pos_x();
}
inline ::google::protobuf::int32 ClientMoveRequest::pos_x() const {
  return pos_x_;
}
inline void ClientMoveRequest::set_pos_x(::google::protobuf::int32 value) {
  set_has_pos_x();
  pos_x_ = value;
}

// required int32 pos_y = 3;
inline bool ClientMoveRequest::has_pos_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ClientMoveRequest::set_has_pos_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ClientMoveRequest::clear_has_pos_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ClientMoveRequest::clear_pos_y() {
  pos_y_ = 0;
  clear_has_pos_y();
}
inline ::google::protobuf::int32 ClientMoveRequest::pos_y() const {
  return pos_y_;
}
inline void ClientMoveRequest::set_pos_y(::google::protobuf::int32 value) {
  set_has_pos_y();
  pos_y_ = value;
}

// -------------------------------------------------------------------

// ClientMoveResponse

// required int32 ret = 1;
inline bool ClientMoveResponse::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClientMoveResponse::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClientMoveResponse::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClientMoveResponse::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 ClientMoveResponse::ret() const {
  return ret_;
}
inline void ClientMoveResponse::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
}

// required int32 map_id = 2;
inline bool ClientMoveResponse::has_map_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ClientMoveResponse::set_has_map_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ClientMoveResponse::clear_has_map_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ClientMoveResponse::clear_map_id() {
  map_id_ = 0;
  clear_has_map_id();
}
inline ::google::protobuf::int32 ClientMoveResponse::map_id() const {
  return map_id_;
}
inline void ClientMoveResponse::set_map_id(::google::protobuf::int32 value) {
  set_has_map_id();
  map_id_ = value;
}

// required int32 pos_x = 3;
inline bool ClientMoveResponse::has_pos_x() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ClientMoveResponse::set_has_pos_x() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ClientMoveResponse::clear_has_pos_x() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ClientMoveResponse::clear_pos_x() {
  pos_x_ = 0;
  clear_has_pos_x();
}
inline ::google::protobuf::int32 ClientMoveResponse::pos_x() const {
  return pos_x_;
}
inline void ClientMoveResponse::set_pos_x(::google::protobuf::int32 value) {
  set_has_pos_x();
  pos_x_ = value;
}

// required int32 pos_y = 4;
inline bool ClientMoveResponse::has_pos_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ClientMoveResponse::set_has_pos_y() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ClientMoveResponse::clear_has_pos_y() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ClientMoveResponse::clear_pos_y() {
  pos_y_ = 0;
  clear_has_pos_y();
}
inline ::google::protobuf::int32 ClientMoveResponse::pos_y() const {
  return pos_y_;
}
inline void ClientMoveResponse::set_pos_y(::google::protobuf::int32 value) {
  set_has_pos_y();
  pos_y_ = value;
}

// -------------------------------------------------------------------

// PlayerLeaveViewNotf

// required int32 player_id = 1;
inline bool PlayerLeaveViewNotf::has_player_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayerLeaveViewNotf::set_has_player_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayerLeaveViewNotf::clear_has_player_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayerLeaveViewNotf::clear_player_id() {
  player_id_ = 0;
  clear_has_player_id();
}
inline ::google::protobuf::int32 PlayerLeaveViewNotf::player_id() const {
  return player_id_;
}
inline void PlayerLeaveViewNotf::set_player_id(::google::protobuf::int32 value) {
  set_has_player_id();
  player_id_ = value;
}

// -------------------------------------------------------------------

// LeavePlayersViewNotf

// repeated int32 player_id = 1;
inline int LeavePlayersViewNotf::player_id_size() const {
  return player_id_.size();
}
inline void LeavePlayersViewNotf::clear_player_id() {
  player_id_.Clear();
}
inline ::google::protobuf::int32 LeavePlayersViewNotf::player_id(int index) const {
  return player_id_.Get(index);
}
inline void LeavePlayersViewNotf::set_player_id(int index, ::google::protobuf::int32 value) {
  player_id_.Set(index, value);
}
inline void LeavePlayersViewNotf::add_player_id(::google::protobuf::int32 value) {
  player_id_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
LeavePlayersViewNotf::player_id() const {
  return player_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
LeavePlayersViewNotf::mutable_player_id() {
  return &player_id_;
}

// -------------------------------------------------------------------

// PlayerEnterViewNotf

// required .PlayerInfo player_info = 1;
inline bool PlayerEnterViewNotf::has_player_info() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PlayerEnterViewNotf::set_has_player_info() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PlayerEnterViewNotf::clear_has_player_info() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PlayerEnterViewNotf::clear_player_info() {
  if (player_info_ != NULL) player_info_->::PlayerInfo::Clear();
  clear_has_player_info();
}
inline const ::PlayerInfo& PlayerEnterViewNotf::player_info() const {
  return player_info_ != NULL ? *player_info_ : *default_instance_->player_info_;
}
inline ::PlayerInfo* PlayerEnterViewNotf::mutable_player_info() {
  set_has_player_info();
  if (player_info_ == NULL) player_info_ = new ::PlayerInfo;
  return player_info_;
}
inline ::PlayerInfo* PlayerEnterViewNotf::release_player_info() {
  clear_has_player_info();
  ::PlayerInfo* temp = player_info_;
  player_info_ = NULL;
  return temp;
}
inline void PlayerEnterViewNotf::set_allocated_player_info(::PlayerInfo* player_info) {
  delete player_info_;
  player_info_ = player_info;
  if (player_info) {
    set_has_player_info();
  } else {
    clear_has_player_info();
  }
}

// -------------------------------------------------------------------

// EnterPlayersViewNotf

// repeated .PlayerInfo player_info = 1;
inline int EnterPlayersViewNotf::player_info_size() const {
  return player_info_.size();
}
inline void EnterPlayersViewNotf::clear_player_info() {
  player_info_.Clear();
}
inline const ::PlayerInfo& EnterPlayersViewNotf::player_info(int index) const {
  return player_info_.Get(index);
}
inline ::PlayerInfo* EnterPlayersViewNotf::mutable_player_info(int index) {
  return player_info_.Mutable(index);
}
inline ::PlayerInfo* EnterPlayersViewNotf::add_player_info() {
  return player_info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PlayerInfo >&
EnterPlayersViewNotf::player_info() const {
  return player_info_;
}
inline ::google::protobuf::RepeatedPtrField< ::PlayerInfo >*
EnterPlayersViewNotf::mutable_player_info() {
  return &player_info_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MSG_ACTION_TYPE>() {
  return ::MSG_ACTION_TYPE_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MessageType>() {
  return ::MessageType_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::DbMessageType>() {
  return ::DbMessageType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
